In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('pet_food_customer_orders.csv')

In [11]:
df

,customer_id,pet_id,pet_order_number,wet_food_order_number,orders_since_first_wet_trays_order,pet_has_active_subscription,pet_food_tier,pet_signup_datetime,pet_allergen_list,pet_fav_flavour_list,...,dental_treat_packs,wet_food_textures_in_order,total_web_sessions,total_web_sessions_since_last_order,total_minutes_on_website,total_minutes_on_website_since_last_order,total_wet_food_updates,total_wet_food_updates_since_last_order,last_customer_support_ticket_date,customer_support_ticket_category
0,1.057480e+19,4.466840e+18,2,1.0,1.0,True,superpremium,00:01.6,NaN,Chicken,...,0,gravy jelly pate,6,4,101,32,0,0,2019-03-16 09:10:12+00:00,proactive
1,1.057480e+19,4.466840e+18,1,NaN,NaN,True,superpremium,00:01.6,NaN,Chicken,...,0,NaN,2,1,69,3,0,0,2019-03-16 09:10:12+00:00,proactive
2,1.057480e+19,4.466840e+18,8,7.0,7.0,True,superpremium,00:01.6,NaN,Chicken,...,0,gravy jelly pate,18,0,184,0,0,0,2019-10-26 06:10:13+00:00,account
3,1.057480e+19,4.466840e+18,4,3.0,3.0,True,superpremium,00:01.6,NaN,Chicken,...,0,gravy jelly pate,13,6,130,15,0,0,2019-04-23 06:28:12+00:00,account
4,1.057480e+19,4.466840e+18,9,8.0,8.0,True,superpremium,00:01.6,NaN,Chicken,...,0,gravy jelly pate,19,1,184,0,0,0,2019-10-26 06:10:13+00:00,account
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49037,1.602640e+18,2.985000e+18,1,NaN,NaN,True,superpremium,00:01.6,beef dairy egg soya wheat,NaN,...,0,NaN,2,2,3,3,0,0,2019-08-08 14:36:23+00:00,account
49038,1.450890e+19,7.874270e+18,1,NaN,NaN,False,superpremium,00:01.6,NaN,NaN,...,0,NaN,1,0,24,0,0,0,NaN,NaN
49039,2.727060e+18,8.164900e+18,1,NaN,NaN,False,premium,00:01.6,NaN,Beef Lamb,...,0,NaN,2,0,44,0,0,0,2019-11-19 10:41:09+00:00,sign_up
49040,1.346850e+19,1.721290e+19,1,1.0,1.0,False,mid,00:01.6,NaN,NaN,...,0,gravy jelly pate,0,0,0,0,0,0,NaN,NaN
49041,1.969550e+18,1.608510e+19,1,NaN,NaN,True,mid,00:01.6,NaN,NaN,...,0,NaN,0,0,0,0,0,0,2019-10-06 18:48:12+00:00,sign_up

In [12]:
import numpy as np
from itertools import chain
labels = np.unique(list(chain(*df['pet_food_tier'].map(lambda x: x.split('|')).tolist())))
labels = [x for x in labels if len(x) > 0]
labels

['mid', 'premium', 'superpremium']

In [13]:
for label in labels:
    if len(label) > 1:
        df[label] = df['pet_food_tier'].map(lambda finding: 1.0 if label in finding else 0.0)

In [14]:
df

,customer_id,pet_id,pet_order_number,wet_food_order_number,orders_since_first_wet_trays_order,pet_has_active_subscription,pet_food_tier,pet_signup_datetime,pet_allergen_list,pet_fav_flavour_list,...,total_web_sessions_since_last_order,total_minutes_on_website,total_minutes_on_website_since_last_order,total_wet_food_updates,total_wet_food_updates_since_last_order,last_customer_support_ticket_date,customer_support_ticket_category,mid,premium,superpremium
0,1.057480e+19,4.466840e+18,2,1.0,1.0,True,superpremium,00:01.6,NaN,Chicken,...,4,101,32,0,0,2019-03-16 09:10:12+00:00,proactive,0.0,1.0,1.0
1,1.057480e+19,4.466840e+18,1,NaN,NaN,True,superpremium,00:01.6,NaN,Chicken,...,1,69,3,0,0,2019-03-16 09:10:12+00:00,proactive,0.0,1.0,1.0
2,1.057480e+19,4.466840e+18,8,7.0,7.0,True,superpremium,00:01.6,NaN,Chicken,...,0,184,0,0,0,2019-10-26 06:10:13+00:00,account,0.0,1.0,1.0
3,1.057480e+19,4.466840e+18,4,3.0,3.0,True,superpremium,00:01.6,NaN,Chicken,...,6,130,15,0,0,2019-04-23 06:28:12+00:00,account,0.0,1.0,1.0
4,1.057480e+19,4.466840e+18,9,8.0,8.0,True,superpremium,00:01.6,NaN,Chicken,...,1,184,0,0,0,2019-10-26 06:10:13+00:00,account,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49037,1.602640e+18,2.985000e+18,1,NaN,NaN,True,superpremium,00:01.6,beef dairy egg soya wheat,NaN,...,2,3,3,0,0,2019-08-08 14:36:23+00:00,account,0.0,1.0,1.0
49038,1.450890e+19,7.874270e+18,1,NaN,NaN,False,superpremium,00:01.6,NaN,NaN,...,0,24,0,0,0,NaN,NaN,0.0,1.0,1.0
49039,2.727060e+18,8.164900e+18,1,NaN,NaN,False,premium,00:01.6,NaN,Beef Lamb,...,0,44,0,0,0,2019-11-19 10:41:09+00:00,sign_up,0.0,1.0,0.0
49040,1.346850e+19,1.721290e+19,1,1.0,1.0,False,mid,00:01.6,NaN,NaN,...,0,0,0,0,0,NaN,NaN,1.0,0.0,0.0
49041,1.969550e+18,1.608510e+19,1,NaN,NaN,True,mid,00:01.6,NaN,NaN,...,0,0,0,0,0,2019-10-06 18:48:12+00:00,sign_up,1.0,0.0,0.0